// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Microsoft.Dynamics365.UIAutomation.Sample.UMA_CRM_Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class StudentEnrollmentsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "StudentEnrollment.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Student Enrollments", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Student Enrollments")))
            {
                global::Microsoft.Dynamics365.UIAutomation.Sample.UMA_CRM_Features.StudentEnrollmentsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole(string user, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "StudentEnrollment",
                    "ValidateAccessToFields",
                    "10625"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate access to Student Enrollment form fields by Role", null, @__tags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given(string.Format("{0} logs-in and navigates to \'Student Enrollment\' Page", user), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then("validate the accessibility of fields on the form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.Then("User should log-out of the Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_Dir@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_Dir@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_Dir@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_DirUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_Dir@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_MIS@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_MIS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_MIS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_MISUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_MIS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_BDR@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_BDR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_BDR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_BDRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_BDR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_GFR@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_GFR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_GFR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_GFRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_GFR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_FD@ultimatemed" +
            "ical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_FD@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_FD@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_FDUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_FD@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_IMS@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_IMS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_IMS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_IMSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_IMS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_AR@ultimatemed" +
            "ical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_AR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_AR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_ARUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_AR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_CAR@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_CAR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_CAR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_CARUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_CAR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_CAAM@ultimatem" +
            "edical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_CAAM@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_CAAM@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_CAAMUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_CAAM@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_WAS@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_WAS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_WAS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_WASUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_WAS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_OBS@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_OBS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_OBS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_OBSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_OBS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_RS@ultimatemed" +
            "ical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_RS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_RS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_RSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_RS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_IntPrep@ultima" +
            "temedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_IntPrep@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_IntPrep@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_IntPrepUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_IntPrep@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_EXA@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_EXA@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_EXA@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_EXAUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_EXA@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_PHTCSA@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_PHTCSA@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_PHTCSA@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_PHTCSAUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_PHTCSA@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_EXC@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_EXC@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_EXC@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_EXCUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_EXC@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_CertS@ultimate" +
            "medical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_CertS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_CertS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_CertSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_CertS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_VS@ultimatemed" +
            "ical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_VS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_VS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_VSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_VS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_VP@ultimatemed" +
            "ical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_VP@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_VP@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_VPUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_VP@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_GSC@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_GSC@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_GSC@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_GSCUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_GSC@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_ISP@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_ISP@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_ISP@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_ISPUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_ISP@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_GSTP@ultimatem" +
            "edical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_GSTP@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_GSTP@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_GSTPUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_GSTP@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_ALMGR@ultimate" +
            "medical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_ALMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_ALMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_ALMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_ALMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_EXTMGR@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_EXTMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_EXTMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_EXTMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_EXTMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_CSMGR@ultimate" +
            "medical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_CSMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_CSMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_CSMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_CSMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_CADMGR@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_CADMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_CADMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_CADMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_CADMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_ASDCAD@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_ASDCAD@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_ASDCAD@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_ASDCADUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_ASDCAD@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_GSTMGR@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_GSTMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_GSTMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_GSTMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_GSTMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_VERMGR@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_VERMGR@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_VERMGR@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_VERMGRUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_VERMGR@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_DIRAL@ultimate" +
            "medical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_DIRAL@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_DIRAL@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_DIRALUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_DIRAL@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_DIRCAD@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_DIRCAD@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_DIRCAD@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_DIRCADUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_DIRCAD@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_DIRCOMPL@ultim" +
            "atemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_DIRCOMPL@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_DIRCOMPL@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_DIRCOMPLUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_DIRCOMPL@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_DIROPS@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_DIROPS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_DIROPS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_DIROPSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_DIROPS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_OPS@ultimateme" +
            "dical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_OPS@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_OPS@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_OPSUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_OPS@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_AViPr@ultimate" +
            "medical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_AViPr@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_AViPr@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_AViPrUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_AViPr@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_ViPr@ultimatem" +
            "edical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_ViPr@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_ViPr@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_ViPrUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_ViPr@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate access to Student Enrollment form fields by Role: CRMTest_SrViPr@ultimat" +
            "emedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Student Enrollments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("StudentEnrollment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ValidateAccessToFields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("10625")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "CRMTest_SrViPr@ultimatemedical.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:User", "CRMTest_SrViPr@ultimatemedical.edu")]
        public virtual void ValidateAccessToStudentEnrollmentFormFieldsByRole_CRMTest_SrViPrUltimatemedical_Edu()
        {
#line 4
this.ValidateAccessToStudentEnrollmentFormFieldsByRole("CRMTest_SrViPr@ultimatemedical.edu", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion

